
DROP POLICY IF EXISTS "Users: self read" ON public.users;
DROP POLICY IF EXISTS "projects read" ON public.projects;
DROP POLICY IF EXISTS "projects insert" ON public.projects;
DROP POLICY IF EXISTS "projects update" ON public.projects;
DROP POLICY IF EXISTS "project_members read" ON public.project_members;
DROP POLICY IF EXISTS "project_members insert" ON public.project_members;
DROP POLICY IF EXISTS "project_members delete" ON public.project_members;
DROP POLICY IF EXISTS "floor_plans read" ON public.floor_plans;
DROP POLICY IF EXISTS "floor_plans insert" ON public.floor_plans;
DROP POLICY IF EXISTS "floor_plans update" ON public.floor_plans;
DROP POLICY IF EXISTS "pins read" ON public.pins;
DROP POLICY IF EXISTS "pins insert" ON public.pins;
DROP POLICY IF EXISTS "pins update" ON public.pins;
DROP POLICY IF EXISTS "products read" ON public.products;
DROP POLICY IF EXISTS "products insert" ON public.products;
DROP POLICY IF EXISTS "products update" ON public.products;
DROP POLICY IF EXISTS "pin_products read" ON public.pin_products;
DROP POLICY IF EXISTS "pin_products insert" ON public.pin_products;
DROP POLICY IF EXISTS "snags read" ON public.snags;
DROP POLICY IF EXISTS "snags insert" ON public.snags;
DROP POLICY IF EXISTS "snags update" ON public.snags;
DROP POLICY IF EXISTS "documents read" ON public.documents;
DROP POLICY IF EXISTS "documents insert" ON public.documents;
DROP POLICY IF EXISTS "tasks read" ON public.tasks;
DROP POLICY IF EXISTS "tasks insert" ON public.tasks;
DROP POLICY IF EXISTS "tasks update" ON public.tasks;
DROP POLICY IF EXISTS "tasks delete" ON public.tasks;
DROP POLICY IF EXISTS "markups read" ON public.markups;
DROP POLICY IF EXISTS "markups insert" ON public.markups;
DROP POLICY IF EXISTS "markups update" ON public.markups;
DROP POLICY IF EXISTS "markups delete" ON public.markups;
DROP POLICY IF EXISTS "floor_plan_versions read" ON public.floor_plan_versions;
DROP POLICY IF EXISTS "floor_plan_versions insert" ON public.floor_plan_versions;
DROP POLICY IF EXISTS "forms read" ON public.forms;
DROP POLICY IF EXISTS "forms insert" ON public.forms;
DROP POLICY IF EXISTS "forms update" ON public.forms;
DROP POLICY IF EXISTS "forms delete" ON public.forms;
DROP POLICY IF EXISTS "form_responses read" ON public.form_responses;
DROP POLICY IF EXISTS "form_responses insert" ON public.form_responses;
DROP POLICY IF EXISTS "form_responses update" ON public.form_responses;
DROP POLICY IF EXISTS "form_responses delete" ON public.form_responses;
DROP POLICY IF EXISTS "feature_toggles read" ON public.feature_toggles;
DROP POLICY IF EXISTS "feature_toggles insert" ON public.feature_toggles;
DROP POLICY IF EXISTS "feature_toggles update" ON public.feature_toggles;
DROP POLICY IF EXISTS "feature_toggles delete" ON public.feature_toggles;

SELECT 'Tables:' as info;
SELECT schemaname, tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename;

SELECT 'Policies:' as info;
SELECT schemaname, tablename, policyname FROM pg_policies WHERE schemaname = 'public' ORDER BY tablename, policyname;
